### ISSUE TITLE
missing docs and docstests on macos

### ISSUE THREAD

**Issue by fabianfreyer** [johalun/sysctl-rs#11]
It seems like it's necessary to repeat the rustdoc comments before the `#[cfg(target_os = "macos")]` macros.

The following will not generate any rustdoc documentation for `foo` on macos, and the docstest will not execute:

```rust
/// such docs, meny wow, amaze
///
/// # Example
/// ```
/// foo();
/// ```
#[cfg(not(target_os="macos"))]
fn foo() {
    println!("bar");
}

#[cfg(target_os="macos")]
fn foo() {
    println!("baz");
}
```

**Comment by johalun** [comment]
Hmm, that sucks..
