### ISSUE TITLE
newest libc broke the crate ...

### ISSUE THREAD

**Issue by przygienda** [johalun/sysctl-rs#22]
having continuous integration would catch stuff like this ... 

arguably they broke the sysctl API (changed mutability)

**Comment by przygienda** [comment]
on 

nightly-x86_64-unknown-linux-gnu

**Comment by johalun** [comment]
This crate is completely untested on Linux from my side. Has it worked before and what version broke it?

**Comment by przygienda** [comment]
aha, that could explain it ... any plans to support it on linux?

**Comment by johalun** [comment]
Patches for Linux are welcome.
