### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by LuoZijun** [johalun/sysctl-rs#24]
Hi, I have made a lot of modifications and simplifications based on this library, and added support for Linux systems. Although @johalun mentioned that he is doing some work in this area, I can't seem to wait any longer :)

If you are interested in this version of my revision, I would be happy to submit a PR.

https://github.com/ExodusVPN/exodus/tree/rewrite/crates/sysctl

https://github.com/ExodusVPN/exodus/blob/rewrite/crates/sysconfig/src/sysctl.rs

**Comment by johalun** [comment]
Hey! I already have a working solution committed. Please check it out (master branch). What missing is updated docs and tests but I'm working on that and plan to release a new version once complete.

**Comment by johalun** [comment]
It's a good idea but sounds like a terrible maintenance burden and you'll never know what sysctl's are added in the future, or added by private kernel modules. Having a cross platform compatible way to simply access all sysctls as string make applications simpler as well. The same sysctl might have different type on unix vs linux.

**Comment by LuoZijun** [comment]
it makes sense :)

i will close PR #23 , and this issue.
