### ISSUE TITLE
Struct interface

### ISSUE THREAD

**Issue by fabianfreyer** [johalun/sysctl-rs#3]
What's your opinion on providing a struct interface, maybe along the following lines:
```
extern crate sysctl;

fn main() {
    let kernversion: sysctl::Ctl = sysctl::Ctl::from_str("kern.osrevision");
    println!("Description: {:?}", kernversion.description());
    println!("Value: {:?}", kernversion.value());
    // etc...
}
```

This would set up the possibility of creating iterators over `Ctl`s, e.g. for iterating through all children of a node.

I understand this would be a breaking API change, so it would probably require a major SemVer bump.

I would start drafting a PR for this.

**Comment by johalun** [comment]
Hi!  Yeah that sounds good. I've been that having iterators would be the next step 👍
