### ISSUE TITLE
Remnant debugging println on FreeBSD?

### ISSUE THREAD

**Issue by StephanvanSchaik** [johalun/sysctl-rs#46]
Using [`sysctl::Ctl::set_value_string`](https://docs.rs/sysctl/0.4.2/sysctl/struct.Ctl.html#method.set_value_string) on FreeBSD causes it to print "type String", which I guess was for debugging purposes. More specifically, this is caused by the line below:

https://github.com/johalun/sysctl-rs/blob/3d1d390e4ab297c5cc99151ca9f868a0c82a7c36/src/unix/ctl.rs#L93

Since I am using this is in another Rust crate, it would be nice if it did not print anything.

**Comment by asomers** [comment]
Yes, I think you're correct.  Would you kindly submit a PR to remove it?

**Comment by StephanvanSchaik** [comment]
Sure, no problem!

**Comment by johalun** [comment]
I just published 0.4.3 which has this line removed. Thanks!
