### ISSUE TITLE
Short reads

### ISSUE THREAD

**Issue by fabianfreyer** [johalun/sysctl-rs#8]
# the issue
Some sysctls, e.g. `vfs.bufspace` on FreeBSD, exaggerate their length, i.e. they report being a `Long`, but read returns only 4 bytes:

```rust
info = CtlInfo { ctl_type: Long, fmt: "L\u{0}", flags: 2147745799 }
```
Attempting to read these will cause a panic, as we are calling `LittleEndian::read_u64` on a `Vec` with less than 8 bytes length.

```
thread 'main' panicked at 'assertion failed: 8 <= buf.len()', [redacted]/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.2.3/src/lib.rs:2024:9
```

# expected behaviour
On short reads, the value should be zero-padded to the size of the target value.

# steps to reproduce

The following program will panic on FreeBSD

```rust
extern crate sysctl;

fn main() {
    let value = sysctl::value("vfs.bufspace");
    println!("vfs.bufspace: {:?}", value);
}
```

**Comment by johalun** [comment]
Good find! Feel free to come up with a fix. I'm a bit swamped with other stuff right now.
